stages:
  - deploy

deploy-dev-job:
  stage: deploy
  script:
    - echo "Generating configuration file..."
    - |
        cat <<EOF > ./apps/main/.env
        NEXT_PUBLIC_API_REST_URL=$NEXT_PUBLIC_API_REST_URL
        NEXT_PUBLIC_API_SECRET_KEY=$NEXT_PUBLIC_API_SECRET_KEY
        NEXT_PUBLIC_API_SOCKET_URL=$NEXT_PUBLIC_API_SOCKET_URL
        NEXT_PUBLIC_SIP_COTURN_URL=$NEXT_PUBLIC_SIP_COTURN_URL
        NEXT_PUBLIC_SIP_COTURN_USER=$NEXT_PUBLIC_SIP_COTURN_USER
        NEXT_PUBLIC_CAPTCHA_SITE_KEY=$NEXT_PUBLIC_CAPTCHA_SITE_KEY
        NEXT_PUBLIC_SIP_COTURN_PASSWORD=$NEXT_PUBLIC_SIP_COTURN_PASSWORD
        NEXT_PUBLIC_SUPPORT_EMAIL_CONTACT=$NEXT_PUBLIC_SUPPORT_EMAIL_CONTACT
        SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
        EOF
    - echo "Starting Docker services..."
    - docker compose -f docker-compose.yml up --build -d
  artifacts:
    paths:
      - ./apps/main/.env
  variables:
    NAME: "autodialer"
    ENV: "dev"
  environment:
    name: $NAME-$ENV
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  tags:
    - docker
    - autodialer-dev
    - shell
    - deploy
#  when: manual


deploy-prod-job:
  stage: deploy
  script:
    - echo "Generating configuration file..."
    - |
        cat <<EOF > ./apps/main/.env
        NEXT_PUBLIC_API_REST_URL=$NEXT_PUBLIC_API_REST_URL
        NEXT_PUBLIC_API_SECRET_KEY=$NEXT_PUBLIC_API_SECRET_KEY
        NEXT_PUBLIC_API_SOCKET_URL=$NEXT_PUBLIC_API_SOCKET_URL
        NEXT_PUBLIC_SIP_COTURN_URL=$NEXT_PUBLIC_SIP_COTURN_URL
        NEXT_PUBLIC_SIP_COTURN_USER=$NEXT_PUBLIC_SIP_COTURN_USER
        NEXT_PUBLIC_SIP_COTURN_PASSWORD=$NEXT_PUBLIC_SIP_COTURN_PASSWORD
        NEXT_PUBLIC_CAPTCHA_SITE_KEY=$NEXT_PUBLIC_CAPTCHA_SITE_KEY
        NEXT_PUBLIC_SIP_COTURN_PASSWORD=$NEXT_PUBLIC_SIP_COTURN_PASSWORD
        NEXT_PUBLIC_SUPPORT_EMAIL_CONTACT=$NEXT_PUBLIC_SUPPORT_EMAIL_CONTACT
        SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
        EOF
    - echo "Starting Docker services..."
    - docker compose -f docker-compose.yml up --build -d
  artifacts:
    paths:
      - ./apps/main/.env
  variables:
    NAME: "autodialer"
    ENV: "prod"
  environment:
    name: $NAME-$ENV
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - docker
    - autodialer-prod
    - shell
    - deploy
  when: manual
