services:
  autodialer-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/apps/main/.next
    #   - /app/apps/main/dist
    env_file:
      - ./apps/main/.env
    command: 'pnpm start-main'
