export const MODAL_NAMES = {
  EDIT_CAMPAIGN: 'EDIT_CAMPAIGN',
  DELETE_CAMPAIGN: 'DELETE_CAMPAIGN',
  DETAILED_REPORT: 'DETAILED_REPORT',
  CREATE_REPORT: 'CREATE_REPORT',
  CREATE_CAMPAIGN: 'CREATE_CAMPAIGN',
  APPROVE_CAMPAIGN: 'APPROVE_CAMPAIGN',
  EDIT_AGENT: 'EDIT_AGENT',
  DELETE_AGENT: 'DELETE_AGENT',
  REVIEW_CAMPAIGN: 'REVIEW_CAMPAIGN',
  CREATE_LEADS_GROUP: 'CREATE_LEADS_GROUP',
} as const

export type TModalNames = typeof MODAL_NAMES[keyof typeof MODAL_NAMES]
