export const MODAL_NAMES = {
  CREATE_CAMPAIGN: 'CREATE_CAMPAIGN',
  EDIT_CAMPAIGN: 'EDIT_CAMPAIGN',
  DELETE_CAMPAIGN: 'DELETE_CAMPAIGN',
  EDIT_AGENT: 'EDIT_AGENT',
  DELETE_AGENT: 'DELETE_AGENT',
  DETAILED_REPORT: 'DETAILED_REPORT',
  CREATE_REPORT: 'CREATE_REPORT',
  APPROVE_CAMPAIGN: 'APPROVE_CAMPAIGN',
  REVIEW_CAMPAIGN: 'REVIEW_CAMPAIGN',
  CREATE_LEADS_GROUP: 'CREATE_LEADS_GROUP',
  EXPORT_ACTIVITY_LOGS: 'EXPORT_ACTIVITY_LOGS',
  EDIT_MANAGER: 'EDIT_MANAGER',
  CAMPAING_INFO: 'CAMPAING_INFO',
} as const

export type TModalNames = typeof MODAL_NAMES[keyof typeof MODAL_NAMES]
