export enum ERoles {
  SUPERADMIN = 'superadmin',
  ADMIN = 'admin',
  AGENT = 'agent',
  MANAGER = 'manager',
}

export enum EPermissions {
  AGENT_PAGE = 'agent_page',
  GET_AGENT = 'get_agent',
  UPDATE_AGENT = 'update_agent',
  DELETE_AGENT = 'delete_agent',
  MANAGER_PAGE = 'manager_page',
  GET_MANAGER = 'get_manager',
  CREATE_MANAGER = 'create_manager',
  UPDATE_MANAGER = 'update_manager',
  DELETE_MANAGER = 'delete_manager',
  GET_API_KEY = 'get_api_key',
  CREATE_CALL = 'create_call',
  CREATE_API_KEY = 'create_api_key',
  CREATE_CAMPAIGN = 'create_campaign',
  GET_CAMPAIGN = 'get_campaign',
  UPDATE_CAMPAIGN = 'update_campaign',
  DELETE_CAMPAIGN = 'delete_campaign',
  START_CAMPAIGN = 'start_campaign',
  STOP_CAMPAIGN = 'stop_campaign',
  CREATE_AGENT = 'create_agent',
  CREATE_LEAD = 'create_lead',
  UPDATE_LEAD = 'update_lead',
  DELETE_LEAD = 'delete_lead',
  GET_LEAD = 'get_lead',
  IMPORT_LEAD = 'import_lead',
  CREATE_ADMIN = 'create_admin',
  UPDATE_ADMIN = 'update_admin',
  DELETE_ADMIN = 'delete_admin',
}
