export const ROUTES = {
  HOME: '/',
  SIGN_IN: '/auth/sign-in',
  FORGOT_PASSWORD: '/auth/forgot-password',
  LOGOUT: '/auth/logout',
  RESET_PASSWORD: '/auth/reset-password',
  DASHBOARD_ACTIVE_CAMPAIGNS: '/cabinet/dashboard/active-campaigns',
  DASHBOARD_ACTIVE_AGENTS: '/cabinet/dashboard/active-agents',
  DASHBOARD_CAMPAIGN_EFFECTIVENESS: '/cabinet/dashboard/campaigns-effectiveness',
  CAMPAIGNS_LIST: '/cabinet/campaigns/list',
  CAMPAIGNS_ANALYTICS: '/cabinet/campaigns/analytics',
  AGENTS_LIST: '/cabinet/agents/list',
  AGENTS_ANALYTICS: '/cabinet/agents/analytics',
  AGENT_CALLS: '/cabinet/agents/calls',
  CREATE_AGENT: '/cabinet/agents/create',
  LEADS_LIST: '/cabinet/leads/list',
  IMPORT_LEADS: '/cabinet/leads/import',
  IMPORT_LEADS_INSTRUCTIONS: '/cabinet/leads/import-instructions',
  SETTINGS_ACCOUNT_MANAGEMENT: '/cabinet/settings/account-management',
  SETTINGS_API_KEY_MANAGEMENT: '/cabinet/settings/api-key-management',
  SETTINGS_ACTIVITY_LOG: '/cabinet/settings/activity-log',
}
