export const ROUTES = {
  HOME: '/',
  SIGN_IN: '/auth/sign-in',
  FORGOT_PASSWORD: '/auth/forgot-password',
  LOGOUT: '/auth/logout',
  RESET_PASSWORD: '/auth/reset-password',
  DASHBOARD_ACTIVE_CAMPAIGNS: '/cabinet/dashboard/active-campaigns',
  DASHBOARD_ACTIVE_AGENTS: '/cabinet/dashboard/active-agents',
  DASHBOARD_CAMPAIGN_EFFECTIVENESS: '/cabinet/dashboard/campaigns-effectiveness',
  CAMPAIGNS_LIST: '/cabinet/campaigns/list',
  CAMPAIGN_VIEW: (campaignId: number): string => `/cabinet/campaigns/view/${campaignId}`,
  CAMPAIGNS_ANALYTICS: '/cabinet/campaigns/analytics',

  AGENTS_LIST: '/cabinet/agents/list',
  AGENTS_ANALYTICS: '/cabinet/agents/analytics',
  AGENT_CALLS: '/cabinet/agents/calls',
  LEADS: '/cabinet/leads',
  LEADS_LIST: '/cabinet/leads/list',
  IMPORT_LEADS: '/cabinet/leads/import',
  IMPORT_LEADS_INSTRUCTIONS: '/cabinet/leads/import-instructions',
  SETTINGS_ADMINS_LIST: '/cabinet/settings/admins-list',
  SETTINGS_ACCOUNT_MANAGEMENT: '/cabinet/settings/account-management',
  SETTINGS_API_KEY_MANAGEMENT: '/cabinet/settings/api-key-management',
  SETTINGS_CAMPAIGNS_MANAGEMENT: '/cabinet/settings/campaigns-management',
  SETTINGS_LEADS_MANAGEMENT: '/cabinet/settings/leads-management',
  SETTINGS_ACTIVITY_LOG_GENERAL: '/cabinet/settings/activity-log/general',
  SETTINGS_ACTIVITY_LOG_CAMPAIGN: '/cabinet/settings/activity-log/campaign',
  MANAGERS_LIST: '/cabinet/managers/list',
  REPORTS_CDR: '/cabinet/reports/cdr',
  REPORTS_CAMPAIGN_DETAILS_INFO: '/cabinet/reports/campaign-details-info',
}
