export const ROUTES = {
  HOME: '/',
  SIGN_IN: '/auth/sign-in',
  FORGOT_PASSWORD: '/auth/forgot-password',
  LOGOUT: 'auth/logout',
  RESET_PASSWORD: '/auth/reset-password',
  DASHBOARD_ACTIVE_CAMPAIGNS: '/dashboard/active-campaigns',
  DASHBOARD_ACTIVE_AGENTS: '/dashboard/active-agents',
  DASHBOARD_CAMPAIGN_EFFECTIVENESS: '/dashboard/campaigns-effectiveness',
  CAMPAIGNS_LIST: '/campaigns/list',
  CAMPAIGNS_ANALYTICS: '/campaigns/analytics',
  AGENTS_LIST: '/agents/list',
  AGENTS_ANALYTICS: '/agents/analytics',
  CREATE_AGENT: '/agents/create',
  LEADS_LIST: '/leads/list',
  IMPORT_LEADS: '/leads/import',
  IMPORT_LEADS_INSTRUCTIONS: '/leads/import-instructions',
  SETTINGS_ACCOUNT_MANAGEMENT: '/settings/account-management',
  SETTINGS_API_KEY_MANAGEMENT: '/settings/api-key-management',
  SETTINGS_ACTIVITY_LOG: '/settings/activity-log',
}
